---
title: "HW6TEST_Jeffrey"
author: "Jack Jeffrey"
format: pdf
editor: visual
---

## Homework 6

# 2.1 Describe Y: PR system

```{r}
setwd("/Users/jackjeffrey/Documents/Poli502_Jeffrey/Data")
world.data <- read.csv("world.csv")
# load data 
table(world.data$pr_sys)
# view table 
```
```{r}
# change labels
world.data$pr <- factor(world.data$pr_sys, 
                        levels = c("Yes", "No"),
                        labels = c("PR System", "Non-PR"))
table(world.data$pr)
# view table for variables
```
# 2.2 Describe X: Ethnic fractionalization
```{r}
table(world.data$frac_eth3)
# view table 
tail(world.data[c("country", "frac_eth3")])
# view table with country names
world.data$frac_eth3_ord <- factor(world.data$frac_eth3, 
                                   levels = c("Low", "Medium", "High"), # order it in this way
                                   ordered = TRUE)
table(world.data$frac_eth3_ord)
# order the variable names
table(world.data$frac_eth3)
table(world.data$frac_eth3_ord)
# compare tables
table(world.data$frac_eth3, world.data$frac_eth3_ord)
# created two-by-two table 
```
# 2.3 Describe X-Y
```{r}
# Ensure gmodels is installed and loaded
if (!require("gmodels")) install.packages("gmodels")
library(gmodels)

# Create CrossTable for PR system and ethnic fractionalization
CrossTable(world.data$pr, world.data$frac_eth3_ord)

# Optional: Run without additional parameters to isolate the issue
CrossTable(world.data$pr, world.data$frac_eth3_ord,
           prop.r = FALSE,     
           prop.t = FALSE,    
           prop.chisq = FALSE, 
           chisq = TRUE)  # Perform chi-square test

# Interpretation: chi-squared equals 4.76 with 2 degrees of freedom and a p-value of 
# 0.092. We could reject the null at a 90% confidence level. 
```
# 3. Correlation
# 3.1 Describe Y: labor freedom
```{r}
summary(world.data$free_labor)
# view statistics for free labor variable, variable has 18 NA's 
if (!require("tidyverse")) install.packages("tidyverse")
library(tidyverse)
# loaded tidyverse package 
g <- ggplot(world.data, aes(x = free_labor)) + geom_histogram()
g <- g + ylab("Number of countries") + xlab("Labor freedom") + theme_bw()
g
# created a graphical summary of number of countries and labor freedom
cleaned_data <- world.data[is.finite(world.data$free_labor), ]
# removed NAs in new object 
cleaned_data <- ggplot(world.data, aes(x = free_labor)) +
                geom_histogram(binwidth = 1) +
                theme_bw()
cleaned_data
# graphed variable without NAs and new binwidth value
```
# 3.2 Describe X: union density
```{r}
summary(world.data$unions)
# numerical summary for union variable, 100 NAs found 
g <- ggplot(world.data, aes(x = unions)) + 
  geom_histogram(na.rm = TRUE) +  # use statbin to remove NAs
  ylab("Number of countries") + 
  xlab("Percent laborers in unions") + 
  theme_bw()
g
# saved the plot
```
# 3.3 Describe X-Y
```{r}
g <- ggplot(world.data, aes(x = unions, y = free_labor)) + geom_point() + theme_bw()
g <- g + ylab("Labor freedom") + xlab("Percent laborers in unions")
g
# plotted an X-Y scatterplot graph using geom_point
```
# Calculate test-statistic & p
```{r}
lab.uni.mat <- as.matrix(world.data[c("unions", "free_labor")])
# create a new matrix 
if (!require("Hmisc")) install.packages("Hmisc")
library(Hmisc)
# loaded Hmisc package 
rcorr(lab.uni.mat, type = "pearson")
# Interpretation: for the Pearson's test we see that the correlation coefficient is 
# positive at 0.18, with a total of 91 observations present in both X and Y variables. 
# The p-value of 0.0913 indicates that our expectations of more labor unions correlating 
# to more labor freedom is statistically significant at the 90% level but not at the 95%.
```
# 4. Adding lines and labels to a graph
```{r}
lab.data <- world.data[!is.na(world.data$unions) & !is.na(world.data$free_labor), ]
# created a new object with NAs removed 
mean.y <- mean(lab.data$free_labor)
mean.x <- mean(lab.data$unions)

mean.y
mean.x
# calculate the means - mean for Y equals 61.66, mean for X equals 24.74

g <- ggplot(lab.data, aes(x = unions, y = free_labor)) + geom_point() + theme_bw()
g <- g + ylab("Labor freedom") + xlab("Percent laborers in unions")
g <- g + geom_hline(aes(yintercept = mean.y))
g <- g + geom_vline(aes(xintercept = mean.x))
g
# scatterplot using hline and vline to draw lines at the X and Y means 

# Optional: Add country labels for readability using ggrepel
if (!require("ggrepel")) install.packages("ggrepel")
library(ggrepel)
options(ggrepel.max.overlaps = Inf)

g <- ggplot(lab.data, aes(x = unions, y = free_labor)) + 
      geom_point() + 
      geom_label_repel(aes(label = country)) +
      ylab("Labor freedom") + xlab("Percent laborers in unions") +
      geom_hline(aes(yintercept = mean.y)) +
      geom_vline(aes(xintercept = mean.x)) +
      theme_bw()
g
# Final scatterplot with country labels for readability
```






